name: Ask Michael to review my code
on: [push]

jobs:
  process-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.set-changed-files.outputs.changed-files }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensures you have the full history for diffing
    - name: Get changed files
      id: set-changed-files
      run: |
        echo "::set-output name=list::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)"
    - name: Ask Michael to review my code
      uses: micmmakarov/reviewer@main
      with:
        file-list: ${{ steps.set-changed-files.outputs.changed-files }}
        github-token: ${{ secrets.THE_GITHUB_TOKEN }}
        openai-token: ${{ secrets.OPENAI_TOKEN }}