name: Ask Michael to review my code
on: [push]

jobs:
  process-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.set-changed-files.outputs.changed-files }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 # Ensures you have the full history for diffing
    - name: Fetch Base and Head Branches
      run: |
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
        git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
    - name: Determine Changed Files
      run: |
        if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
          # This is the first push or a force push to a new branch, consider all files
          echo "CHANGED_FILES=$(git ls-tree -r --name-only HEAD | tr '\n' ' ')" >> $GITHUB_ENV
        else
          # Compare to the previous commit
          echo "CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | tr '\n' ' ')" >> $GITHUB_ENV
        fi
    - name: Ask Michael to review my code
      uses: micmmakarov/reviewer@main
      with:
        file-list: ${{ env.CHANGED_FILES }}
        github-token: ${{ secrets.THE_GITHUB_TOKEN }}
        openai-token: ${{ secrets.OPENAI_TOKEN }}