name: Ask Michael to review my code
on: [pull_request]

jobs:
  process-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-files: ${{ steps.set-changed-files.outputs.changed-files }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Ensures you have the full history for diffing
    - name: Fetch Base and Head Branches
      run: |
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
        git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
    - name: Determine Changed Files
      run: |
        git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} > file_list.txt |
        git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }}
    - name: Ask Michael to review my code
      uses: micmmakarov/reviewer@main
      with:
        file-list: ${{ github.workspace }}/file_list.txt
        github-token: ${{ secrets.THE_GITHUB_TOKEN }}
        openai-token: ${{ secrets.OPENAI_TOKEN }}